# This workflow will install Python dependencies, run tests and lint with multiple versions of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Flake8 and Pytest

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "example_images/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "example_images/**"

permissions:
  contents: read

jobs:
  lint-and-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        uv sync
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        uv run flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Run testing server
      run: |
        uv run testing_server.py &
    - name: Test with pytest
      run: |
        uv run pytest
